"""empty message

Revision ID: 04a21f4d08b7
Revises: 199bb6d42220
Create Date: 2021-11-30 16:05:36.987798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04a21f4d08b7'
down_revision = '199bb6d42220'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cargas', 'previsao_entrega',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cargas', 'previsao_entrega',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
