"""empty message

Revision ID: 0e251b5c59da
Revises: 
Create Date: 2021-12-10 17:21:16.613417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e251b5c59da'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('motoristas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('sobrenome', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('celular', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('cpf', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('cnh', sa.String(length=11), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('localizacao', sa.String(), nullable=True),
    sa.Column('motorista_ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('celular'),
    sa.UniqueConstraint('cnh'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('sobrenome', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('cpf', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('celular', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('usuario_ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('celular'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email')
    )
    op.create_table('caminhoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('marca', sa.String(), nullable=False),
    sa.Column('modelo', sa.String(), nullable=False),
    sa.Column('capacidade_de_carga', sa.Float(), nullable=False),
    sa.Column('placa', sa.String(), nullable=False),
    sa.Column('motorista_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['motorista_id'], ['motoristas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('placa')
    )
    op.create_table('cargas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('disponivel', sa.Boolean(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('destino', sa.String(), nullable=True),
    sa.Column('origem', sa.String(), nullable=False),
    sa.Column('horario_saida', sa.DateTime(), nullable=True),
    sa.Column('horario_chegada', sa.DateTime(), nullable=True),
    sa.Column('previsao_entrega', sa.String(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('caminhao_id', sa.Integer(), nullable=True),
    sa.Column('dono_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['caminhao_id'], ['caminhoes.id'], ),
    sa.ForeignKeyConstraint(['dono_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cargas_categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('carga_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['carga_id'], ['cargas.id'], ),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cargas_categorias')
    op.drop_table('cargas')
    op.drop_table('caminhoes')
    op.drop_table('usuarios')
    op.drop_table('motoristas')
    op.drop_table('categorias')
    # ### end Alembic commands ###
