"""empty message

Revision ID: 4bed0bce0bd5
Revises: f547c11372f1
Create Date: 2021-12-13 20:45:19.938017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bed0bce0bd5'
down_revision = 'f547c11372f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('avaliacoes_usuario_motorista',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nota', sa.Float(), nullable=False),
    sa.Column('motorista_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['motorista_id'], ['motoristas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('motorista_id'),
    sa.UniqueConstraint('usuario_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('avaliacoes_usuario_motorista')
    # ### end Alembic commands ###
