"""empty message

Revision ID: 4fd116670ab9
Revises: a8b50352c69a
Create Date: 2021-12-13 11:23:40.085951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fd116670ab9'
down_revision = 'a8b50352c69a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('super_adm', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'super_adm')
    # ### end Alembic commands ###
