"""empty message

Revision ID: 6eefacbbe6cd
Revises: 4bed0bce0bd5
Create Date: 2021-12-13 21:34:43.293871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6eefacbbe6cd'
down_revision = '4bed0bce0bd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entregas_realizadas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('carga_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['carga_id'], ['cargas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('carga_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entregas_realizadas')
    # ### end Alembic commands ###
