"""empty message

Revision ID: a0c2ab8f1426
Revises: 9e5a79f1ad06
Create Date: 2021-12-10 15:38:33.609359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0c2ab8f1426'
down_revision = '9e5a79f1ad06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('motoristas', sa.Column('email', sa.String(), nullable=False))
    op.add_column('motoristas', sa.Column('celular', sa.String(), nullable=False))
    op.add_column('motoristas', sa.Column('motorista_ativo', sa.Boolean(), nullable=False))
    op.create_unique_constraint(None, 'motoristas', ['email'])
    op.create_unique_constraint(None, 'motoristas', ['celular'])
    op.add_column('usuarios', sa.Column('usuario_ativo', sa.Boolean(), nullable=False))
    op.create_unique_constraint(None, 'usuarios', ['email'])
    op.create_unique_constraint(None, 'usuarios', ['celular'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuarios', type_='unique')
    op.drop_constraint(None, 'usuarios', type_='unique')
    op.drop_column('usuarios', 'usuario_ativo')
    op.drop_constraint(None, 'motoristas', type_='unique')
    op.drop_constraint(None, 'motoristas', type_='unique')
    op.drop_column('motoristas', 'motorista_ativo')
    op.drop_column('motoristas', 'celular')
    op.drop_column('motoristas', 'email')
    # ### end Alembic commands ###
