"""empty message

Revision ID: acc2792f9489
Revises: 0be3a9e9bd3d
Create Date: 2021-12-11 23:51:32.569649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acc2792f9489'
down_revision = '0be3a9e9bd3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('motoristas', sa.Column('latitude', sa.String(), nullable=True))
    op.add_column('motoristas', sa.Column('longitude', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('motoristas', 'longitude')
    op.drop_column('motoristas', 'latitude')
    # ### end Alembic commands ###
