"""motorista_id e usuario_id == unique

Revision ID: f547c11372f1
Revises: 4fd116670ab9
Create Date: 2021-12-13 15:41:54.794481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f547c11372f1'
down_revision = '4fd116670ab9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'usuarios_inativos', ['usuario_id'])
    op.create_unique_constraint(None, 'usuarios_inativos', ['motorista_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuarios_inativos', type_='unique')
    op.drop_constraint(None, 'usuarios_inativos', type_='unique')
    # ### end Alembic commands ###
