"""empty message

Revision ID: f7f226b2b14e
Revises: 2bcb2106b74f
Create Date: 2021-11-30 15:16:00.704732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7f226b2b14e'
down_revision = '2bcb2106b74f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('motoristas', 'localizacao',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('motoristas', 'localizacao',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
